### ISSUE TITLE
Investigate access to the Oracle environment

### ISSUE THREAD

**Issue by stvnrlly** [VermontAHS/Authorization#3]
- [x] send request for access
- [x] check out the sample API (below)

**Comment by SeamusLoftus** [comment]
Could make a hit against this sample Oracle API:
https://docs.cloud.oracle.com/iaas/api/#/en/identity/20160918/

**Comment by stvnrlly** [comment]
It looks like the sample APIs require an account with a subscription, so we can't just experiment with them.

Once we have access, it looks like [`defined_tags`](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/identity/models/oci.identity.models.User.html#oci.identity.models.User.defined_tags) and [`freeform_tags`](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/identity/models/oci.identity.models.User.html#oci.identity.models.User.freeform_tags) are likely to be where the data we want is.
